version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: malati_app
    restart: always
    ports:
      - "3005:3000"
    volumes:
      # Mount the data folder so JSON files and SQLite DB persist if the container restarts
      - ./data:/data
    env_file:
      - .env
